version: '3.8'
networks:
  mynetwork:
    driver: bridge
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  quoteservice:
    image: oskarskalski/quote-service:latest
    restart: always
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - ENVIRONMENT=db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - mynetwork


  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECRUITY_ADMIN_USER=adminjakubjedrzejak
      - GF_SECRUITY_ADMIN_PASSWORD=PaSSw0rd12345JakubJedrzejak
      - GF_USER_ALLOW_SIGN_UP=true
    ports:
      - 3000:3000
    networks:
      - mynetwork